spring.application.name=employeeapp


#spring.cache.type=simple
# ===============================
# = DATA SOURCE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/employeecompany
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA / HIBERNATE
# ===============================


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# ===============================
# = SERVER
# ===============================

server.port=8080

spring.cache.type=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379