spring.application.name=api_gateway

server.port=8888

##user
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8083
#spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
#
##product
#spring.cloud.gateway.routes[1].id=product-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**
#
##payment
#spring.cloud.gateway.routes[2].id=payment-service
#spring.cloud.gateway.routes[2].uri=http://localhost:8081
#spring.cloud.gateway.routes[2].predicates[0]=Path=/payment/**


eureka.client.serviceUrl.defaultZone=http://localhost:8067/registry/eureka


#enable dynamic rooutings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled= true