spring.application.name=config-server


server.servlet.context-path=/config

server.port=9999

spring.cloud.config.server.git.uri=https://github.com/vamsi239/cloud-config3.git

#http://localhost:9999/configserver/app/default