spring.application.name=service_registery

server.port=8067
server.servlet.context-path=/registry


#to remove self regi of eureka server
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
